"""Show what tailoring actually changed.

The verifier proves nothing was invented. This shows what was *done* — which
bullets were reworded, which were moved up, what vocabulary was introduced.
Together they let someone audit a tailored CV in about thirty seconds instead
of reading two documents side by side and trying to hold both in their head.

The comparison is at the level of bullets and sentences rather than characters,
because "this bullet was reworded" is the unit a person actually reviews. A
word-level diff of a rewritten sentence is unreadable noise.
"""

from __future__ import annotations

import difflib
import re

from pydantic import BaseModel, Field

#: Below this ratio two lines are different bullets, not a rewording of one.
_REWORD_THRESHOLD = 0.38

#: Lines shorter than this are headings or fragments, not content worth diffing.
_MIN_LINE = 12


class LineChange(BaseModel):
    """One bullet or sentence that differs between the two CVs."""

    kind: str  # "reworded" | "added" | "dropped"
    before: str = ""
    after: str = ""
    similarity: float = 0.0


class TailoringDiff(BaseModel):
    """A structured account of how the tailored CV differs from the original."""

    changes: list[LineChange] = Field(default_factory=list)
    kept: int = 0
    new_terms: list[str] = Field(default_factory=list)

    @property
    def reworded(self) -> list[LineChange]:
        return [c for c in self.changes if c.kind == "reworded"]

    @property
    def added(self) -> list[LineChange]:
        return [c for c in self.changes if c.kind == "added"]

    @property
    def dropped(self) -> list[LineChange]:
        return [c for c in self.changes if c.kind == "dropped"]

    def summary(self) -> str:
        return (
            f"{len(self.reworded)} reworded · {len(self.added)} added · "
            f"{len(self.dropped)} not carried over · {self.kept} unchanged"
        )

    def as_markdown(self) -> str:
        lines = [
            "# What Tailoring Changed",
            "",
            self.summary(),
            "",
            "Every line below came from your original CV unless marked as added.",
            "Read the *added* section most carefully — that is where a tool could",
            "put words in your mouth.",
            "",
        ]

        if self.new_terms:
            lines += ["## Vocabulary introduced for this role", ""]
            lines.append(", ".join(f"`{term}`" for term in self.new_terms))
            lines += [
                "",
                "These words appear in the tailored CV but not in your original.",
                "They should be a fairer description of the same work — not a new claim.",
                "",
            ]

        if self.reworded:
            lines += ["## Reworded", ""]
            for change in self.reworded:
                lines += [
                    f"- **Was:** {change.before}",
                    f"  **Now:** {change.after}",
                    "",
                ]

        if self.added:
            lines += ["## Added", ""]
            lines += [f"- {c.after}" for c in self.added] + [""]

        if self.dropped:
            lines += ["## Not carried over", ""]
            lines += [f"- {c.before}" for c in self.dropped] + [""]
            lines += [
                "Dropped lines are usually the least relevant to this role, which is",
                "the point of tailoring — but check nothing important was lost.",
                "",
            ]

        lines += ["> Generated by OfferPrinter's tailoring diff.", ""]
        return "\n".join(lines)


_BULLET_RE = re.compile(r"^([-*]\s+|\d+\.\s+)")


def _content_lines(text: str) -> list[str]:
    """Bullets and paragraphs worth comparing, stripped of Markdown furniture.

    Source CVs are usually hard-wrapped, so raw lines are fragments rather than
    units of meaning. Continuation lines are joined back onto their bullet or
    paragraph first — otherwise the diff reports half-sentences and reads as
    nonsense.
    """
    blocks: list[str] = []
    current: list[str] = []

    def flush() -> None:
        if current:
            block = re.sub(r"\s+", " ", " ".join(current)).strip()
            block = re.sub(r"\*\*(.+?)\*\*", r"\1", block).strip()
            if len(block) >= _MIN_LINE:
                blocks.append(block)
            current.clear()

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith(">"):
            flush()
            continue
        if _BULLET_RE.match(line):
            flush()  # a new bullet always starts a new block
            current.append(_BULLET_RE.sub("", line))
        else:
            current.append(line)  # a wrapped continuation of the block above
    flush()
    return blocks


def _tokens(text: str) -> set[str]:
    return set(re.findall(r"[a-z][a-z0-9.+#-]{2,}", text.lower()))


def diff_cv(original: str, tailored: str) -> TailoringDiff:
    """Compare an original CV against its tailored version."""
    before = _content_lines(original)
    after = _content_lines(tailored)

    diff = TailoringDiff()
    matcher = difflib.SequenceMatcher(a=before, b=after, autojunk=False)

    unmatched_before: list[str] = []
    unmatched_after: list[str] = []

    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            diff.kept += i2 - i1
        elif tag == "delete":
            unmatched_before.extend(before[i1:i2])
        elif tag == "insert":
            unmatched_after.extend(after[j1:j2])
        elif tag == "replace":
            unmatched_before.extend(before[i1:i2])
            unmatched_after.extend(after[j1:j2])

    # Pair up what is really the same bullet, reworded. Greedy best-match is
    # plenty here: CVs have tens of bullets, not thousands.
    remaining_after = list(unmatched_after)
    for old in unmatched_before:
        best, best_ratio = None, 0.0
        for new in remaining_after:
            ratio = difflib.SequenceMatcher(a=old.lower(), b=new.lower()).ratio()
            if ratio > best_ratio:
                best, best_ratio = new, ratio
        if best is not None and best_ratio >= _REWORD_THRESHOLD:
            diff.changes.append(
                LineChange(kind="reworded", before=old, after=best, similarity=round(best_ratio, 3))
            )
            remaining_after.remove(best)
        else:
            diff.changes.append(LineChange(kind="dropped", before=old))

    for new in remaining_after:
        diff.changes.append(LineChange(kind="added", after=new))

    # Vocabulary present in the tailored CV but not the original.
    diff.new_terms = sorted(_tokens(tailored) - _tokens(original))[:40]
    return diff
