"""Write a generated package to disk as .md, .docx and/or .pdf, plus a combined file.

Kept separate from generation so the format concerns live in one place. The
.docx writer does a lightweight Markdown-to-Word rendering (headings, bullets,
bold) — enough to produce clean, ATS-friendly documents without a heavy
dependency. The .pdf writer is our own (see `pdf_writer.py`), for the same
reason: recruiters ask for PDFs and ATS parsers want plain Helvetica text.
"""

from __future__ import annotations

import re
from pathlib import Path

from offerprinter.models.schemas import ApplicationPackage, Artifact
from offerprinter.services.pdf_writer import write_pdf

#: Output formats `write_package` knows how to produce.
SUPPORTED_FORMATS = ("md", "docx", "pdf")


def _write_md(artifact: Artifact, folder: Path) -> Path:
    path = folder / f"{artifact.filename}.md"
    path.write_text(artifact.content.rstrip() + "\n", encoding="utf-8")
    return path


def _write_pdf(artifact: Artifact, folder: Path) -> Path:
    return write_pdf(artifact.content, folder / f"{artifact.filename}.pdf")


_BOLD_RE = re.compile(r"\*\*(.+?)\*\*")


def _add_markdown_runs(paragraph, text: str) -> None:
    """Add text to a python-docx paragraph, honouring **bold** spans."""
    pos = 0
    for m in _BOLD_RE.finditer(text):
        if m.start() > pos:
            paragraph.add_run(text[pos : m.start()])
        run = paragraph.add_run(m.group(1))
        run.bold = True
        pos = m.end()
    if pos < len(text):
        paragraph.add_run(text[pos:])


def _write_docx(artifact: Artifact, folder: Path) -> Path:
    from docx import Document

    doc = Document()
    for raw_line in artifact.content.splitlines():
        line = raw_line.rstrip()
        if not line:
            doc.add_paragraph()
            continue
        if line.startswith("### "):
            doc.add_heading(line[4:], level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:], level=1)
        elif line.lstrip().startswith(("- ", "* ")):
            stripped = line.lstrip()[2:]
            p = doc.add_paragraph(style="List Bullet")
            _add_markdown_runs(p, stripped)
        elif re.match(r"^\d+\.\s", line.lstrip()):
            stripped = re.sub(r"^\d+\.\s", "", line.lstrip())
            p = doc.add_paragraph(style="List Number")
            _add_markdown_runs(p, stripped)
        else:
            p = doc.add_paragraph()
            _add_markdown_runs(p, line)

    path = folder / f"{artifact.filename}.docx"
    doc.save(str(path))
    return path


def _combined_markdown(package: ApplicationPackage) -> str:
    parts = [f"# Application Package — {package.role} at {package.company}\n"]
    parts.append(
        "> Generated by OfferPrinter. Every statement is drawn from your real CV — "
        "nothing here is fabricated. Review before sending.\n"
    )
    if package.fit:
        parts.append(f"\n**Fit score: {package.fit.score}/100 — {package.fit.band}.** ")
        parts.append(f"{package.fit.verdict}\n")
    if package.verification is not None:
        mark = "✅" if package.verification.passed else "⚠️"
        parts.append(f"\n{mark} **Fabrication check:** {package.verification.summary()}\n")
    for artifact in package.artifacts:
        parts.append("\n---\n")
        parts.append(artifact.content.rstrip())
    return "\n".join(parts) + "\n"


def write_package(
    package: ApplicationPackage, output_dir: str, formats: list[str]
) -> dict[str, list[Path]]:
    """Write every artifact in the requested formats. Returns paths written.

    Returns a dict mapping artifact key (plus "_combined") to the list of files
    written for it.
    """
    folder = Path(output_dir) / package.slug
    folder.mkdir(parents=True, exist_ok=True)

    def write_all(artifact: Artifact) -> list[Path]:
        paths: list[Path] = []
        if "md" in formats:
            paths.append(_write_md(artifact, folder))
        if "docx" in formats:
            paths.append(_write_docx(artifact, folder))
        if "pdf" in formats:
            paths.append(_write_pdf(artifact, folder))
        return paths

    written: dict[str, list[Path]] = {}
    for artifact in package.artifacts:
        written[artifact.key] = write_all(artifact)

    # The fit score is structured data rather than a generated document, so it
    # gets rendered here rather than coming back from the model as Markdown.
    if package.fit:
        written["fit_score"] = write_all(
            Artifact(
                key="fit_score",
                title="Fit Score",
                filename="fit-score",
                content=package.fit.as_markdown(),
            )
        )

    if package.verification is not None:
        written["verification"] = write_all(
            Artifact(
                key="verification",
                title="Fabrication Check",
                filename="fabrication-check",
                content=package.verification.as_markdown(),
            )
        )

    if package.diff:
        written["diff"] = write_all(
            Artifact(
                key="diff",
                title="What Tailoring Changed",
                filename="tailoring-diff",
                content=package.diff,
            )
        )

    # Combined package — a single file with everything.
    written["_combined"] = write_all(
        Artifact(
            key="_combined",
            title="Full Package",
            filename="full-package",
            content=_combined_markdown(package),
        )
    )

    return written
