"""Write a generated package to disk as .md and/or .docx, plus a combined file.

Kept separate from generation so the format concerns live in one place. The
.docx writer does a lightweight Markdown-to-Word rendering (headings, bullets,
bold) — enough to produce clean, ATS-friendly documents without a heavy
dependency.
"""

from __future__ import annotations

import re
from pathlib import Path

from offerprinter.models.schemas import ApplicationPackage, Artifact


def _write_md(artifact: Artifact, folder: Path) -> Path:
    path = folder / f"{artifact.filename}.md"
    path.write_text(artifact.content.rstrip() + "\n", encoding="utf-8")
    return path


_BOLD_RE = re.compile(r"\*\*(.+?)\*\*")


def _add_markdown_runs(paragraph, text: str) -> None:
    """Add text to a python-docx paragraph, honouring **bold** spans."""
    pos = 0
    for m in _BOLD_RE.finditer(text):
        if m.start() > pos:
            paragraph.add_run(text[pos : m.start()])
        run = paragraph.add_run(m.group(1))
        run.bold = True
        pos = m.end()
    if pos < len(text):
        paragraph.add_run(text[pos:])


def _write_docx(artifact: Artifact, folder: Path) -> Path:
    from docx import Document

    doc = Document()
    for raw_line in artifact.content.splitlines():
        line = raw_line.rstrip()
        if not line:
            doc.add_paragraph()
            continue
        if line.startswith("### "):
            doc.add_heading(line[4:], level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:], level=1)
        elif line.lstrip().startswith(("- ", "* ")):
            stripped = line.lstrip()[2:]
            p = doc.add_paragraph(style="List Bullet")
            _add_markdown_runs(p, stripped)
        elif re.match(r"^\d+\.\s", line.lstrip()):
            stripped = re.sub(r"^\d+\.\s", "", line.lstrip())
            p = doc.add_paragraph(style="List Number")
            _add_markdown_runs(p, stripped)
        else:
            p = doc.add_paragraph()
            _add_markdown_runs(p, line)

    path = folder / f"{artifact.filename}.docx"
    doc.save(str(path))
    return path


def _combined_markdown(package: ApplicationPackage) -> str:
    parts = [f"# Application Package — {package.role} at {package.company}\n"]
    parts.append(
        "> Generated by OfferPrinter. Every statement is drawn from your real CV — "
        "nothing here is fabricated. Review before sending.\n"
    )
    for artifact in package.artifacts:
        parts.append("\n---\n")
        parts.append(artifact.content.rstrip())
    return "\n".join(parts) + "\n"


def write_package(
    package: ApplicationPackage, output_dir: str, formats: list[str]
) -> dict[str, list[Path]]:
    """Write every artifact in the requested formats. Returns paths written.

    Returns a dict mapping artifact key (plus "_combined") to the list of files
    written for it.
    """
    folder = Path(output_dir) / package.slug
    folder.mkdir(parents=True, exist_ok=True)

    written: dict[str, list[Path]] = {}
    for artifact in package.artifacts:
        paths: list[Path] = []
        if "md" in formats:
            paths.append(_write_md(artifact, folder))
        if "docx" in formats:
            paths.append(_write_docx(artifact, folder))
        written[artifact.key] = paths

    # Combined package (Markdown) — a single file with everything.
    combined = Artifact(
        key="_combined",
        title="Full Package",
        filename="full-package",
        content=_combined_markdown(package),
    )
    combined_paths: list[Path] = []
    if "md" in formats:
        combined_paths.append(_write_md(combined, folder))
    if "docx" in formats:
        combined_paths.append(_write_docx(combined, folder))
    written["_combined"] = combined_paths

    return written
