#!/usr/bin/env python3
"""Generate the Homebrew formula, resource blocks and all.

Homebrew installs Python CLIs into their own virtualenv, which means the
formula has to pin *every* transitive dependency with a URL and a sha256.
Maintaining that by hand is miserable and goes stale the moment a dependency
releases, so this regenerates the whole formula from what PyPI currently
serves:

    python scripts/make_homebrew_formula.py 0.2.0 > packaging/homebrew/offerprinter.rb

It resolves the real dependency set by installing the published package into a
throwaway virtualenv, then looks up each distribution's source archive on PyPI.
This is the same job `brew update-python-resources` does, without needing
Homebrew installed to run it.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

import httpx

PYPI = "https://pypi.org/pypi/{name}/json"

#: Installed into every venv by the tooling itself; never a real dependency.
SKIP = {"pip", "setuptools", "wheel", "offerprinter"}


def pypi_metadata(name: str, version: str | None = None) -> dict:
    """Fetch a distribution's PyPI metadata (httpx, so certifi handles TLS)."""
    url = PYPI.format(name=name)
    if version is not None:
        url = url[: -len("json")] + f"{version}/json"
    response = httpx.get(url, timeout=30, follow_redirects=True)
    response.raise_for_status()
    return response.json()


def source_archive(name: str, version: str) -> tuple[str, str]:
    """Return (url, sha256) of a distribution's sdist, falling back to a wheel.

    Homebrew prefers sdists. A few projects publish wheels only; for those a
    pure-Python wheel still installs correctly inside the virtualenv.
    """
    data = pypi_metadata(name, version)
    urls = data["urls"]

    for entry in urls:
        if entry["packagetype"] == "sdist":
            return entry["url"], entry["digests"]["sha256"]

    for entry in urls:
        if entry["filename"].endswith("-py3-none-any.whl"):
            return entry["url"], entry["digests"]["sha256"]

    raise SystemExit(f"No installable source archive found for {name} {version}")


def resolve_dependencies(version: str) -> list[tuple[str, str]]:
    """Install offerprinter into a temp venv and report what came with it."""
    with tempfile.TemporaryDirectory() as tmp:
        venv = Path(tmp) / "venv"
        subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True, capture_output=True)
        python = venv / "bin" / "python"
        subprocess.run(
            [str(python), "-m", "pip", "install", "-q", f"offerprinter=={version}"],
            check=True,
            capture_output=True,
        )
        listing = subprocess.run(
            [str(python), "-m", "pip", "list", "--format=json"],
            check=True,
            capture_output=True,
            text=True,
        )

    packages = json.loads(listing.stdout)
    resolved = [
        (pkg["name"], pkg["version"]) for pkg in packages if pkg["name"].lower() not in SKIP
    ]
    return sorted(resolved, key=lambda pair: pair[0].lower())


def render(version: str) -> str:
    main_url, main_sha = source_archive("offerprinter", version)
    dependencies = resolve_dependencies(version)

    resources = []
    for name, dep_version in dependencies:
        url, sha = source_archive(name, dep_version)
        resources.append(f'  resource "{name}" do\n    url "{url}"\n    sha256 "{sha}"\n  end\n')

    return f'''# Homebrew formula for OfferPrinter.
#
# Generated by scripts/make_homebrew_formula.py — do not hand-edit the resource
# blocks. To update after a release:
#
#   python scripts/make_homebrew_formula.py <version> > packaging/homebrew/offerprinter.rb
#
# Then copy this file into the `homebrew-tap` repository as
# Formula/offerprinter.rb, so that users can:
#
#   brew tap mohitagw15856/tap
#   brew install offerprinter

class Offerprinter < Formula
  include Language::Python::Virtualenv

  desc "Print a tailored CV, cover letter, fit memo and ATS report from one job description"
  homepage "https://github.com/mohitagw15856/OfferPrinter"
  url "{main_url}"
  sha256 "{main_sha}"
  license "MIT"
  head "https://github.com/mohitagw15856/OfferPrinter.git", branch: "main"

  depends_on "python@3.12"

{chr(10).join(resources)}
  def install
    virtualenv_install_with_resources
  end

  def caveats
    <<~EOS
      OfferPrinter needs an LLM API key. Set one of:

        export ANTHROPIC_API_KEY="sk-ant-..."   # default provider
        export OPENAI_API_KEY="sk-..."
        export GEMINI_API_KEY="..."
        export MOONSHOT_API_KEY="..."

      Or run it with no key at all against a local model:

        ollama pull llama3.1
        offerprinter --provider ollama --cv cv.pdf --jd-file jd.txt

      The Streamlit web UI is not installed by this formula. For it:

        pip install "offerprinter[web]"
    EOS
  end

  test do
    assert_match "OfferPrinter", shell_output("#{{bin}}/offerprinter --version")
    system bin/"offerprinter", "--help"
  end
end
'''


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: make_homebrew_formula.py <version>")
    sys.stdout.write(render(sys.argv[1]))
